
[general]
# RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
RemoteNickFormat="[{NICK}@{PROTOCOL}] "
StripNick=false

[irc]
    [irc.freenode]
    Server="irc.freenode.net:6697"
    Nick="matterbot3"
    UseTLS=true

    [irc.freenode2]
    Server="irc.freenode.net:6697"
    Nick="matterbot2"
    UseTLS=true

[tox]
    [tox.fixlan]
    Server="ddd"
    Nick="toxync"


[[gateway]]
name="gateway2"
enable=false
    [[gateway.inout]]
    account="tox.fixlan"
    channel="test autobot"
    passive=true

    #[[gateway.inout]]
    #account="irc.freenode"
    #channel="#testk"

[[gateway]]
name="gateway-tox-en"
enable=true

    [[gateway.inout]]
    account="tox.fixlan"
    channel="Tox Public Chat"

[[gateway]]
name="gateway-tox-cn"
enable=true

    [[gateway.inout]]
    account="tox.fixlan"
    channel="Chinese 中文"

[[gateway]]
name="gateway-tox-ru"
enable=false

    [[gateway.inout]]
    account="tox.fixlan"
    channel="Club Cyberia: No Pedos or Pervs"

[[gateway]]
name="gateway-#linuxba"
enable=true

    [[gateway.inout]]
    account="tox.fixlan"
    channel="#linuxba"

[[gateway]]
name="gateway-#archlinux-cn"
enable=true

    [[gateway.inout]]
    account="tox.fixlan"
    channel="#archlinux-cn"

[[gateway]]
name="gateway-#archlinux-cn-offtopic"
enable=true

    [[gateway.inout]]
    account="tox.fixlan"
    channel="#archlinux-cn-offtopic"

[[gateway]]
name="gateway-#testk"
enable=false

    [[gateway.inout]]
    account="tox.fixlan"
    channel="#testk"

[[gateway]]
name="gateway-#rtab123"
enable=false

    [[gateway.inout]]
    account="tox.fixlan"
    channel="#rtab123"

[[gateway]]
name="gateway1"
enable=false
    [[gateway.inout]]
    account="irc.freenode"
    channel="#testk"

    [[gateway.inout]]
    account="irc.freenode2"
    channel="#rtab123"
